#!/bin/sh
#
# setup.sh
# ========
# Setup script to configure a new device
#
# Requires
# - git

# Enforce requirements

echo 'Checking dependencies...'
which git > /dev/null 2>&1 || echo 'Git is not installed!' && exit 1

echo 'Changing to home directory...'
# Go to the home directory
cd $HOME

# Clone the configuration repo
echo 'Cloning configuration repo'
git clone https://github.com/ndrewtl/dotfiles.git .config

# Setup zsh and bash
echo 'Setting up shell'
cat << EOF > .bashrc
  #!/bin/bash
  # Generated by setup.sh

  source $HOME/.config/bash/bootstrap.sh
EOF

cat << EOF > .zshrc
  #!/bin/zsh
  # Generated by setup.sh

  source $HOME/.config/zsh/bootstrap.sh
EOF

